---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: install node
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash - && sudo apt-get install -y nodejs
- name: "Install zip utility."
  become: yes
  apt:
    name: [ "zip", "unzip" ]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
#added extra
- name: Run node migration
  shell: |
    echo "migration started"
    cd /home/unbuntu/backend
    npm run migrations > migration_output.txt
    cat migration_output.txt 
- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend --start
